vw4tools: VirtualWisdom4ClientTool Class Reference
VirtualWisdom4ClientTool Class Reference
VirtualWisdom4ClientTool is a "Swiss Army Knife" of tools used when working with VirtualWisdom4.
Data Structures
interface EntitySelector
simple convenience interface to allow entity selection to be codified and created on-the-fly in a query API
Public Member Functions
VirtualWisdom4ClientTool (String xmlFile)
Class Constructor to create with an initial file to load.
VirtualWisdom4ClientTool ()
Class Constructor with no initial file.
boolean check ()
self-check whether dependent components are available.
TreeMap< String, Entity > entities ()
void load (String filename)
Wrapper to just load the file, spitting out exceptions and stacks as they occur.
Vector< Pattern > patterns ()
String prettyJSON (VWImport v)
Convenience function to generate a pretty-printed JSON text string.
void save (String filename)
Wrapper to just save the file, spitting out exceptions and stacks as they occur.
void setTarget (String ver)
Set the expected version of the receiving VirtualWisdom to tailor version-specific features.
WWNDescription wwndesc ()
Static Public Member Functions
static void main (String args[])
Main function, as you can tell.
static String report (int orphans, int fostered, int total)
Convenience function to sSummarize the current "coverage" or efficiency of alias/nicknames onto current entities as human-readable text; useful to show whether the patterns used to aggregate leaf-entities into upper-layer entities are being effective at all.
Data Fields
VWImport vwimport = null
singleton list of JSON-writable objects accessed through vwimport()
Protected Member Functions
void _load (String filename) throws java.io.IOException
Open a file.
void _save (String filename) throws java.lang.Exception
Save the current XML Document to a new file.
void loadAndAbsorbFile (String f)
one-shot load a new file and absorb the contents: open the file and stream the contents at an array of parsers, the one with the best results wins; using that result, absorb all alias information, attempting to create parent storagecontroller(s) or hosts as resulting from absorbtion patterns
void loadAndRemoveFile (String f)
one-shot load a new file and remove the contents from the internal list of leafEntities (HBAs, FAs)
VWImport vwimport ()
Protected Attributes
TreeMap< String, Entity > entities = null
local singleton array accessed from entities()
Vector< Pattern > patterns = null
local singleton array accessed from patterns()
WWNDescription wwndesc = null
local singleton array accessed from wwndesc()
Private Attributes
org.w3c.dom.Document xmlDocument
eventually used to hold an XML document when converting XML<–>JSON<–>XML
Detailed Description
VirtualWisdom4ClientTool is a "Swiss Army Knife" of tools used when working with VirtualWisdom4.
The existence of these tools is not a judgement on VirtualWisdom4's proper Engineering; rather, an acceptance that a faster-response solution for the longer-tail of the normal curve is often helpful swapping QA delay for reduced customer friction.
As you'd expect, there is no support for this. If it breaks, you may choose to keep both pieces :)
Ad-Hoc content for this utility-stack may appear at http://fcfae.com/
Definition at line 62 of file VirtualWisdom4ClientTool.java.
Constructor & Destructor Documentation
VirtualWisdom4ClientTool (String xmlFile) inline
Class Constructor to create with an initial file to load.
Parameters
xmlFile File to load at start
See also
load(String)
Definition at line 91 of file VirtualWisdom4ClientTool.java.
References VirtualWisdom4ClientTool.load().
Member Function Documentation
void _load (String filename) throws java.io.IOException inline protected
Open a file.
This is actually a wrapper for the underlying file load
Parameters
filename file to load
Exceptions
IOException when File() encounters an error instaitating (typically path or permissions)
Todo:
: evaluate: mapper.configure(DeserializationConfig.Feature.FAIL_ON_UNKNOWN_PROPERTIES, false);
Definition at line 120 of file VirtualWisdom4ClientTool.java.
Referenced by VirtualWisdom4ClientTool.load().
void _save (String filename) throws java.lang.Exception inline protected
Save the current XML Document to a new file.
Parameters
filename filename to save into
Definition at line 155 of file VirtualWisdom4ClientTool.java.
Referenced by VirtualWisdom4ClientTool.save().
boolean check () inline
self-check whether dependent components are available.
This is beyond the benefits of build-time link verification and run-time linking, but checking the sanity of dependent parts. For example – and the only initial check – BouncyCastle may be available as a Provider (bcpkix) but may not load successfully for a number of fussy little reasons; I'd like to be able to check each one and improve in-field diagnostics.
Returns
boolean: Am I sane?
Definition at line 464 of file VirtualWisdom4ClientTool.java.
Referenced by VirtualWisdom4ClientTool.main().
TreeMap<String,Entity> entities () inline
< singleton access for entities
Returns
collection of entities
Definition at line 218 of file VirtualWisdom4ClientTool.java.
Referenced by VirtualWisdom4ClientTool.loadAndAbsorbFile().
void load (String filename) inline
Wrapper to just load the file, spitting out exceptions and stacks as they occur.
Parameters
filename file to load
Definition at line 134 of file VirtualWisdom4ClientTool.java.
References VirtualWisdom4ClientTool._load().
Referenced by VirtualWisdom4ClientTool.main(), and VirtualWisdom4ClientTool.VirtualWisdom4ClientTool().
void loadAndAbsorbFile (String f) inline protected
one-shot load a new file and absorb the contents: open the file and stream the contents at an array of parsers, the one with the best results wins; using that result, absorb all alias information, attempting to create parent storagecontroller(s) or hosts as resulting from absorbtion patterns
Parameters
f name of file to open
See also
https://github.com/chickenandpork/fibrechannel-parsers/
Definition at line 585 of file VirtualWisdom4ClientTool.java.
References VirtualWisdom4ClientTool.entities(), Entity.name, Entity.setDescription(), Entity.setname(), and VirtualWisdom4ClientTool.wwndesc().
Referenced by VirtualWisdom4ClientTool.main().
void loadAndRemoveFile (String f) inline protected
one-shot load a new file and remove the contents from the internal list of leafEntities (HBAs, FAs)
Working on only the leaf entities, this uses the parser array to parse an input stream, and for each WWPN found, it removes that leaf entity from the system. It doesn't affect the child_entities of referring entities to allow for a loaded entity list to still refer to entities which are already on the target system.
Parameters
f name of file to open
See also
https://github.com/chickenandpork/fibrechannel-parsers/
Definition at line 505 of file VirtualWisdom4ClientTool.java.
Referenced by VirtualWisdom4ClientTool.main().
static void main (String args[]) inline static
Main function, as you can tell.
this function merely parses the command-line to dispatch actions to the meat of the meal above. I'm using an actual GetOpt because, yes, I'm a UNIX/C hack, re-using 3-decades-old knowledge, but this also preserves both extensibility and the ability to use longopts in scripts as a way to self-document what the tool's doing.
No real intelligence herein except the parse-and-redirect action.
Parameters
args as you'd expect, these are commandline arguments given when the jar is activated
Always always ALWAYS provide a quick reference and a version output
Commandline Options:
-H|–help Show a simple help screen as a reminder of options which are understood by the application
Commandline Options:
java -jar vw4tools.jar --help
Commandline Options:
-V|–version Show the current release version for reference
Commandline Options:
java -jar vw4tools.jar --version
 1.0-7
Commandline Options:
-n|–nicknameout={file} Output nicknames from internal store
Commandline Options:
-o|–output={file} Output nicknames from internal store –nicknameout and –output are currently functionally identical; they both cause the internal nickname/entity base to be written out as JSON with the exception of a few "magic" filenames:
Commandline Options:
schema.json will cause the current schema to be written
Commandline Options:
orderedtuples.csv will cause an OrderedTuples.csv file to be written, suitable for post-processing via csv-to-json.awk but allowing a user to more easily edit CSV for fine-tuning
Commandline Options:
orphanentities.csv will cause a CSV to be written listing all orphan entities. An "Orphan Entity" is an entity lacking a parent entity, such as an "HBA Port" without a "host" parent, or a "iomodule" without a parent "storagearray" entity.
Commandline Options:
All other filename patterns will result in a JSON-formatted file
Commandline Options:
-N|–nickname={file/uri} Import nicknames by parsing a text stream from various sources
Commandline Options:
java -jar vw4tools.jar --nickname=switch44.zoneshow
      Parse results for AliShowZoneParser:
      Zones: 44
      Aliases: 112 (names with one or more WWPNs)
      Aliases: 136 (name/WWPN tuples)
In this example, a zone file was parsed by the AliShowZoneParser resulting in 112 nicknames; due to duplicate nicknames, there are actually 136 unique WWPN/alias tuples, which means that (136-112) 24 of the WWPNs have the same alias as other WWPNs
Commandline Options:
-i|–input import an existing JSON file for later editing
Commandline Options:
-r|–read import an existing JSON file for later editing
Commandline Options:
java -jar vw4tools.jar --read working.json
Commandline Options:
-R|–remove Parse nicknames for removal from the internal nickname list
Commandline Options:
-R|–removenicknames Parse nicknames for removal from the internal nickname list
Commandline Options:
-t|–target set a target version for JSON output. Defaults to latest supported. A value of 4.0.1 is converted to 40.1 internally due to float comparison and expected changed every bump of major/minor version
Commandline Options:
-!|–report Summarize the current status of the internal nicknaes and pattern/collation coverage
Commandline Options:
java -jar vw4tools.jar --nickname=switch44.zoneshow  --report
(vw4tools) parsed 0 zones, 2 aliases via Alias4Parser
vw4tools 1.0-7
    5 total entities
    4 leaf nodes
    2 orphans
50.00 % coverage
Commandline Options:
-P|–pattern= is used to provide an "aggregating pattern" to collect Orphan Entities into a container. An "Orphan Entity" is an entity which is not part of a larger device: an HBA not assigned to a host, or a FA not assigned to a storage array. Aggregating Patterns are evaluated immediately, so their order amidst other command options to import or remove entities is important.
Commandline Options:
-p|–checkpattern= is used to test an "aggregating pattern" against a certain nickname/alias. Although Aggregating Patterns are evaluated immediately, they're stored for testing as well, so even though we're giving a test alias after the pattern, it'll evaluate all loaded patterns against the alias:
Commandline Options:
 java -jar vw4tools.jar --pattern="([^-]+)-[^-]+$" --checkpattern=NetApp-123456 --checkpattern=UberServer_44_HBA0
"NetApp-123456" --> "NetApp"
"UberServer_44_HBA0" --> "UberServer_44_HBA0"
Commandline Options:
in this example, the one pattern it tested against a new alias when the –checkpattern is encountered; if there were two patterns, each pattern would be tried to the checkpattern sample when seen:
Commandline Options:
 java -jar vw4tools.jar --pattern="([^-]+)-[^-]+$" --pattern="^(.*)_hba(\d+)$" --checkpattern=NetApp-123456 --checkpattern=UberServer_44_hba0
"NetApp-123456" --> "NetApp"
"NetApp-123456" --> "NetApp-123456"
"UberServer_44_HBA0" --> "UberServer_44_hba0"
"UberServer_44_HBA0" --> "UberServer_44"
Commandline Options:
in this example, two patterns ("([^-]+)-[^-]+$" and "^(.*)_hba(\d+)$") are loaded; when "NetApp-123456" is given as a checkpattern, each is tried in turn, so we see that "([^-]+)-[^-]+$" converts "NetApp-123456" to "NetApp", which means a bunch of devices "NetApp-123456", "NetApp-123457", "NetApp-ABCDEF" would be child entities of a larger entity "NetApp". In essence, all the NetApp-* are collected into the same contailer called "NetApp". Similarly, "([^-]+)-[^-]+$" and "^(.*)_hba(\d+)$" are tested against "UberServer_44_hba0" when the checkpattern is given, and we can see that "([^-]+)-[^-]+$" makes no difference to the value, but "^(.*)_hba(\d+)$" has the desired effect of chopping off the "_hba#" portion.
Todo:
need to check 3-decimal values such as "-t 4.0.1.7" (see also testsuite.at.in)
Definition at line 970 of file VirtualWisdom4ClientTool.java.
References VirtualWisdom4ClientTool.check(), Entity.description, VirtualWisdom4ClientTool.entities, VirtualWisdom4ClientTool.load(), VirtualWisdom4ClientTool.loadAndAbsorbFile(), VirtualWisdom4ClientTool.loadAndRemoveFile(), Entity.name, VirtualWisdom4ClientTool.report(), VirtualWisdom4ClientTool.setTarget(), VirtualWisdom4ClientTool.VirtualWisdom4ClientTool(), and VirtualWisdom4ClientTool.vwimport.
Vector<Pattern> patterns () inline
< singleton access for patterns
Returns
collection of patterns
Definition at line 211 of file VirtualWisdom4ClientTool.java.
String prettyJSON (VWImport v) inline
Convenience function to generate a pretty-printed JSON text string.
Parameters
v VWImport object to markup
Returns
a pretty-printed JSON using ObjectWriter.withDefaultPrettyPrinter() or null if an exception occurs
Definition at line 185 of file VirtualWisdom4ClientTool.java.
static String report (int orphans, int fostered, int total) inline static
Convenience function to sSummarize the current "coverage" or efficiency of alias/nicknames onto current entities as human-readable text; useful to show whether the patterns used to aggregate leaf-entities into upper-layer entities are being effective at all.
Returns
formatted string showing summary in human-readable text
Parameters
orphans count of orphan entities (still lacking parent entities)
fostered count of entities accepted by parent entities
total count of all entities in the system
Definition at line 429 of file VirtualWisdom4ClientTool.java.
Referenced by VirtualWisdom4ClientTool.main().
void save (String filename) inline
Wrapper to just save the file, spitting out exceptions and stacks as they occur.
Parameters
filename filename to save into
Definition at line 166 of file VirtualWisdom4ClientTool.java.
References VirtualWisdom4ClientTool._save().
void setTarget (String ver) inline
Set the expected version of the receiving VirtualWisdom to tailor version-specific features.
Parameters
ver version to set (ie "4.0", "4.0.0", "4.0.2")
JVM Options:
debug.showCompatTarget causes the compat.target to be displayed when (re)set
Definition at line 71 of file VirtualWisdom4ClientTool.java.
References Entity.compatibilityVersion.
Referenced by VirtualWisdom4ClientTool.main().
VWImport vwimport () inline protected
< singleton to access vwimport to allow for later post-process
Returns
vwimport instance, created if needed
Definition at line 106 of file VirtualWisdom4ClientTool.java.
Referenced by VirtualWisdom4ClientTool.main().
WWNDescription wwndesc () inline
< singleton access for wwndesc
Returns
wwndesc
Definition at line 225 of file VirtualWisdom4ClientTool.java.
Referenced by VirtualWisdom4ClientTool.loadAndAbsorbFile().
The documentation for this class was generated from the following file:
java/VirtualWisdom4ClientTool.java