vw4tools: Entity.LeafEntity Class Reference
Entity.LeafEntity Class Reference
A LeafEntity is the common ancestor of Storage FAs and Server HBAs; this is combined only so that leaves can be treated in common.
Public Member Functions
LeafEntity (String name, String wwn)
Class Constructor with an initial child to absorb.
Entity newParent (String name)
create a new Entity of the correct class to be a parent of this one: this function is stubbed to return null so that this class can be a static class and directly extensible.
String parentName ()
convenience function: if this entity has a parent, show the parent's name, otherwise show this entity's name.
String wwn ()
the unique WWPN of the hba: getter for internal variable
Public Member Functions inherited from Entity
Entity (String name)
Class Constructor with no initial child.
Entity (String name, Entity e) throws ImproperChildException
Class Constructor with an initial child to absorb.
String description ()
the description of the entity showing source
void maybeAdopt (Entity e) throws ImproperChildException
Convenience function: Entity should either adopt a given child "e" or throw an exception.
String name ()
unique name of the entity: getter for internal variable
abstract Entity newParent (String name)
create a new Entity of the correct class to be a parent of this one.
void setDescription (String description)
set the description of the entity to show its source: setter pattern
void setname (String name)
set the unique name of the entity: setter
Protected Member Functions
boolean canBeChild (Entity e)
whether a given entity can be this entity's child
org.smallfoot.vw4.VWImport.Entity vwentity (String tag)
create a bogus function to avoid build errors
Protected Member Functions inherited from Entity
abstract boolean canBeChild (Entity e)
whether a given entity can be this entity's child
Vector< Entity > children ()
get a list of child entities (local access to local singleton .children)
abstract
org.smallfoot.vw4.VWImport.Entity vwentity (String tag)
create a streamable JSON entity from this one
Protected Attributes
String wwn
the unique WWPN of the hba
Protected Attributes inherited from Entity
Vector< Entity > children = null
local singleton late-instantiated as needed by children()
String description
the description of the entity showing source
String name
the unique name of the entity
WeakReference< Entity > parent = null
convenience weak-reference to parent: I want a reference but not one that will block GC
Additional Inherited Members
Static Public Member Functions inherited from Entity
static String compatibilityVersion ()
convert the compatibilityVersion into a string
static String compatibilityVersion (String newVersion)
set a new compatibility string to set a different target version
Static Protected Member Functions inherited from Entity
static int _compatibilityVersion ()
calculate the compatibilityVersion as required
Static Protected Attributes inherited from Entity
static Integer compatibilityVersion = null
singleton-used compatibility: if (re)set to null, _compatibilityVersion() recalculates
Detailed Description
A LeafEntity is the common ancestor of Storage FAs and Server HBAs; this is combined only so that leaves can be treated in common.
Definition at line 276 of file Entity.java.
Constructor & Destructor Documentation
LeafEntity (String name, String wwn) inline
Class Constructor with an initial child to absorb.
Parameters
name initial name of the new entity
wwn initial child entity for this Leaf Entity
Definition at line 307 of file Entity.java.
References Entity.LeafEntity.wwn().
Member Function Documentation
boolean canBeChild (Entity e) inline protected
whether a given entity can be this entity's child
Returns
true if accepted, false if refused. LeafEntity has no children so this method will always be false
Parameters
e entity to check for possible descendent-hood
Returns
true if this entity accepts children of "e"'s descendent type (always false for Leaf Entity)
Definition at line 320 of file Entity.java.
Entity newParent (String name) inline
create a new Entity of the correct class to be a parent of this one: this function is stubbed to return null so that this class can be a static class and directly extensible.
Not really 100% good practice, but the descendency of this LeafEntity is intended to collect functionality. This class is wrapped inside an Entity to retain a clear affinity, but thence needs to be static to be extensible. "She swallowed the cat to catch the spider, she swallowed the spider to catch the fly.. "
Descendents will override this method
Returns
new parent for this entity
Parameters
name initial name of the new entity
Definition at line 345 of file Entity.java.
String parentName () inline
convenience function: if this entity has a parent, show the parent's name, otherwise show this entity's name.
Used during OrderedTuples written via VirtualWisdom4ClientTool.writeOrderedTuples(String, EntitySelector), this allows a simpler, consistent coding when OrderedTuples is being exported.
Returns
name of parent entity is existent, otherwise name of this entity
Definition at line 293 of file Entity.java.
References Entity.name().
String wwn () inline
the unique WWPN of the hba: getter for internal variable
Returns
the WWPN
Definition at line 280 of file Entity.java.
Referenced by Entity.LeafEntity.LeafEntity(), EntityHBA.vwentity(), and EntityFA.vwentity().
The documentation for this class was generated from the following file:
java/Entity.java