vw4tools: EntityArray Class Reference
EntityArray Class Reference
An EntityArray is the representation of an Array entity in the JSON import for VW4.
Public Member Functions
EntityArray (String name, Entity e) throws ImproperChildException
Basic Class Constructor.
Entity newParent (String name)
create a new Entity of the correct class to be a parent of this one
Public Member Functions inherited from Entity
Entity (String name)
Class Constructor with no initial child.
Entity (String name, Entity e) throws ImproperChildException
Class Constructor with an initial child to absorb.
String description ()
the description of the entity showing source
void maybeAdopt (Entity e) throws ImproperChildException
Convenience function: Entity should either adopt a given child "e" or throw an exception.
String name ()
unique name of the entity: getter for internal variable
abstract Entity newParent (String name)
create a new Entity of the correct class to be a parent of this one.
void setDescription (String description)
set the description of the entity to show its source: setter pattern
void setname (String name)
set the unique name of the entity: setter
Protected Member Functions
boolean canBeChild (Entity e)
whether a given entity can be this entity's child
org.smallfoot.vw4.VWImport.Entity vwentity (String tag)
create a streamable JSON entity from this one
Protected Member Functions inherited from Entity
abstract boolean canBeChild (Entity e)
whether a given entity can be this entity's child
Vector< Entity > children ()
get a list of child entities (local access to local singleton .children)
abstract
org.smallfoot.vw4.VWImport.Entity vwentity (String tag)
create a streamable JSON entity from this one
Additional Inherited Members
Protected Attributes inherited from Entity
Vector< Entity > children = null
local singleton late-instantiated as needed by children()
String description
the description of the entity showing source
String name
the unique name of the entity
WeakReference< Entity > parent = null
convenience weak-reference to parent: I want a reference but not one that will block GC
Detailed Description
An EntityArray is the representation of an Array entity in the JSON import for VW4.
Be very careful: there is an Entity, and a VWImport::Entity
Definition at line 44 of file EntityArray.java.
Member Function Documentation
boolean canBeChild (Entity e) inline protected
whether a given entity can be this entity's child
Returns
true if accepted, false if refused
Parameters
e entity to check for possible descendent-hood
Definition at line 55 of file EntityArray.java.
org.smallfoot.vw4.VWImport.Entity vwentity (String tag) inline protected
create a streamable JSON entity from this one
Returns
a org.smallfoot.vw4.VWImport.Entity representation of this instance
Parameters
tag default tag to apply
Definition at line 61 of file EntityArray.java.
References Entity.children(), Entity.description(), and Entity.name().
The documentation for this class was generated from the following file:
java/EntityArray.java