vw4tools: EntityFA Class Reference
EntityFA Class Reference
An EntityFA is the representation of an Storage FA entity in the JSON import for VW4.
Public Member Functions
EntityFA (String name, String wwn)
Class Constructor with no initial child.
String wwn ()
getter
Public Member Functions inherited from Entity
Entity (String name)
Class Constructor with no initial child.
Entity (String name, Entity e) throws ImproperChildException
Class Constructor with an initial child to absorb.
String description ()
getter
String name ()
getter
void setDescription (String description)
setter
void setname (String name)
setter
Protected Member Functions
boolean canBeChild (Entity e)
this entity has no children so this method will always be false
org.smallfoot.vw4.VWImport.Entity vwentity ()
create a streamable JSON entity from this one
Protected Member Functions inherited from Entity
abstract boolean canBeChild (Entity e)
whether a given entity can be this entity's child
Vector< Entity > children ()
local access to local singleton .children
abstract
org.smallfoot.vw4.VWImport.Entity vwentity ()
create a streamable JSON entity from this one
Protected Attributes
String wwn
the unique WWPN of the hba
Protected Attributes inherited from Entity
Vector< Entity > children = null
local singleton late-instantiated as needed by children()
String description
the description of the entity showing source
String name
the unique name of the entity
WeakReference< Entity > parent = null
convenience weak-reference to parent: I want a reference but not one that will block GC
Detailed Description
An EntityFA is the representation of an Storage FA entity in the JSON import for VW4.
Be very careful: there is an Entity, and a VWImport::Entity
Definition at line 44 of file EntityFA.java.
Member Function Documentation
org.smallfoot.vw4.VWImport.Entity vwentity () inline protected
create a streamable JSON entity from this one
Returns
a org.smallfoot.vw4.VWImport.Entity representation of this instance
Definition at line 62 of file EntityFA.java.
References Entity.description(), Entity.name(), and EntityFA.wwn().
The documentation for this class was generated from the following file:
java/EntityFA.java