vw4tools: Entity Class Reference
Entity Class Reference abstract
An Entity is the core mutable object used in the JSON import for VW4.
Data Structures
class ImproperChildException
Descendents of Entity should know whether a given entity can be one of their child elements.
class LeafEntity
A LeafEntity is the common ancestor of Storage FAs and Server HBAs; this is combined only so that leaves can be treated in common.
Public Member Functions
Entity (String name)
Class Constructor with no initial child.
Entity (String name, Entity e) throws ImproperChildException
Class Constructor with an initial child to absorb.
String description ()
the description of the entity showing source
void maybeAdopt (Entity e) throws ImproperChildException
Convenience function: Entity should either adopt a given child "e" or throw an exception.
String name ()
unique name of the entity: getter for internal variable
abstract Entity newParent (String name)
create a new Entity of the correct class to be a parent of this one.
void setDescription (String description)
set the description of the entity to show its source: setter pattern
void setname (String name)
set the unique name of the entity: setter
Static Public Member Functions
static String compatibilityVersion ()
convert the compatibilityVersion into a string
static String compatibilityVersion (String newVersion)
set a new compatibility string to set a different target version
Protected Member Functions
abstract boolean canBeChild (Entity e)
whether a given entity can be this entity's child
Vector< Entity > children ()
get a list of child entities (local access to local singleton .children)
abstract
org.smallfoot.vw4.VWImport.Entity vwentity (String tag)
create a streamable JSON entity from this one
Static Protected Member Functions
static int _compatibilityVersion ()
calculate the compatibilityVersion as required
Protected Attributes
Vector< Entity > children = null
local singleton late-instantiated as needed by children()
String description
the description of the entity showing source
String name
the unique name of the entity
WeakReference< Entity > parent = null
convenience weak-reference to parent: I want a reference but not one that will block GC
Static Protected Attributes
static Integer compatibilityVersion = null
singleton-used compatibility: if (re)set to null, _compatibilityVersion() recalculates
Detailed Description
An Entity is the core mutable object used in the JSON import for VW4.
I'm not so sure how it'll unfold yet, but I intend to treat all hosts and hbas and storagecontrollers and iomodules as similar objects: things that can have children things. In the short term, be very careful: there is an Entity, and a VWImport::Entity
Definition at line 46 of file Entity.java.
Constructor & Destructor Documentation
Entity (String name) inline
Class Constructor with no initial child.
Parameters
name initial name of the new entity
Definition at line 196 of file Entity.java.
References Entity.name().
Entity (String name, Entity e) throws ImproperChildException inline
Class Constructor with an initial child to absorb.
Parameters
name initial name of the new entity
e Entity to consider for adoption as child
Definition at line 207 of file Entity.java.
References Entity.maybeAdopt(), and Entity.name().
Member Function Documentation
static int _compatibilityVersion () inline static protected
calculate the compatibilityVersion as required
Returns
integer value of compatibilityVersion
JVM Options:
compat.target (values: X.Y.Z as a version. For example: 4.0.1, 4.1, 4, 4.2) can be used to tell the JSON output to use specific features available on later versions of the VirtualWisdom4 product. Initially controls whether fcport entities are created but may expand.
Definition at line 58 of file Entity.java.
References Entity.compatibilityVersion().
Referenced by Entity.compatibilityVersion(), EntityHBA.vwentity(), and EntityFA.vwentity().
abstract boolean canBeChild (Entity e) abstract protected
whether a given entity can be this entity's child
Parameters
e entity to check for possible descendent-hood
Returns
true if this entity accepts children of "e"'s descendent type
Referenced by Entity.maybeAdopt().
Vector<Entity> children () inline protected
get a list of child entities (local access to local singleton .children)
Returns
list of zero or more child entities but never null
Definition at line 140 of file Entity.java.
Referenced by Entity.maybeAdopt(), EntityHost.vwentity(), and EntityArray.vwentity().
static String compatibilityVersion () inline static
convert the compatibilityVersion into a string
Returns
string value of compatibilityVersion
Definition at line 95 of file Entity.java.
References Entity._compatibilityVersion().
Referenced by Entity._compatibilityVersion(), and Entity.compatibilityVersion().
static String compatibilityVersion (String newVersion) inline static
set a new compatibility string to set a different target version
This, with compatibilityVersion() and _compatibilityVersion(), is a lot of scaffolding around compatibility outputs; I'm both trying to give some versatility here, plus experimenting myself with properties-vs-commandlines-vs-both. At the end of the day, both methods work to set a version for output, initially a determiner whether fcport entities are produced. There's future possibility for growth, including config/properties files, afforded by this massive 4-part scaffolding with delusions of grandeur.
Parameters
newVersion the new value to use as a version
Returns
previous config version
Definition at line 114 of file Entity.java.
References Entity.compatibilityVersion().
String description () inline
the description of the entity showing source
Returns
description of the entity
Definition at line 160 of file Entity.java.
Referenced by Entity.setDescription(), EntityHBA.vwentity(), EntityFA.vwentity(), EntityArray.vwentity(), and EntityHost.vwentity().
void maybeAdopt (Entity e) throws ImproperChildException inline
Convenience function: Entity should either adopt a given child "e" or throw an exception.
This allows very simple coding of streamlining the adoption in a cleaner iteration loop.
Parameters
e Entity to consider for adoption as child
Definition at line 218 of file Entity.java.
References Entity.canBeChild(), Entity.children(), and Entity.parent.
Referenced by Entity.Entity().
String name () inline
unique name of the entity: getter for internal variable
Returns
the name
Definition at line 148 of file Entity.java.
Referenced by Entity.Entity(), EntityArray.EntityArray(), EntityHost.EntityHost(), Entity.LeafEntity.parentName(), Entity.setname(), EntityFA.vwentity(), EntityHBA.vwentity(), EntityHost.vwentity(), and EntityArray.vwentity().
abstract Entity newParent (String name) abstract
create a new Entity of the correct class to be a parent of this one.
This function is used to polymorphically create the parentage of an entity such as the host holding an HBA
Returns
new parent for this entity
Parameters
name initial name of the new entity
void setDescription (String description) inline
set the description of the entity to show its source: setter pattern
Parameters
description the description to set
Definition at line 165 of file Entity.java.
References Entity.description().
Referenced by VirtualWisdom4ClientTool.loadAndAbsorbFile().
void setname (String name) inline
set the unique name of the entity: setter
Parameters
name the name to set
Definition at line 153 of file Entity.java.
References Entity.name().
Referenced by VirtualWisdom4ClientTool.loadAndAbsorbFile().
abstract org.smallfoot.vw4.VWImport.Entity vwentity (String tag) abstract protected
create a streamable JSON entity from this one
Returns
a org.smallfoot.vw4.VWImport.Entity representation of this instance
Parameters
tag default tag to apply
The documentation for this class was generated from the following file:
java/Entity.java